#
# NOTE: THIS DOCKERFILE IS GENERATED MANUALLY
#
# FEEL FREE TO EDIT IT.
#

FROM webdevops/ansible:ubuntu-16.04

RUN apt-get update && apt-get -y install yamllint \
    && rm -rf /var/lib/apt/lists/*

